name: Android QA build

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  if_merged:
    if: github.events.pull_request.merged == true

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Building APKs
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APKs and Bundle
        uses: actions/upload-artifact@v1
        with:
          name: Test-1
          path: app/build/outputs/
