name: Android CI

on:
  pull_request:
    branches: [ "dev","pre-master" ]
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug apk
      run: ./gradlew assembleDebug --stacktrace
    - name: Upload APKs
      uses: actions/upload-artifact@v3
      with:
        name: 56ConsumerApp
        path: app/build/outputs/
